sudo: required
language: cpp
dist: bionic

before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install doxygen
- sudo apt-get install graphviz
- sudo apt-get install libdlib-dev
- sudo apt-get install libblas-dev
- sudo apt-get install liblapack-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target package
- doxygen
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local-dir: doxygen/html
  on:
    all_branches: true

- provider: script
  skip_cleanup: true
  on:
    all_branches: true
  script:
    curl -T property_recomendation-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -umakerslet:$BINTRAY_API_KEY "https://api.bintray.com/content/makerslet/property_recomendation/package/$TRAVIS_BUILD_NUMBER/property_recomendation-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
